# Generated by Django 5.0.6 on 2026-09-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_order_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedasset",
            name="slot_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="slot_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="generatedasset",
            name="kind",
            field=models.CharField(
                choices=[("preview", "Preview"), ("final", "Final")],
                default="preview",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="generationjob",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("preview", "Preview"),
                    ("revision", "Revision"),
                    ("full", "Full production"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("awaiting_photos", "Awaiting photos"),
                    ("ready_for_checkout", "Ready for checkout"),
                    ("awaiting_payment", "Awaiting payment"),
                    ("paid", "Paid"),
                    ("preview_generating", "Preview generating"),
                    ("internal_preview_review", "Internal preview review"),
                    ("preview_review", "Preview review"),
                    ("revision_requested", "Revision requested"),
                    ("revision_generating", "Revision generating"),
                    ("pack_generating", "Pack generating"),
                    ("quality_control", "Quality control"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="generationjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("task_type", "full")),
                fields=("order", "slot_key", "attempt"),
                name="uniq_full_slot_attempt",
            ),
        ),
    ]
