# Generated by Django 5.0.6 on 2026-09-17 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_full_generation"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("order.status_changed", "Order status changed"),
                            (
                                "preview.customer_approved",
                                "Preview approved by customer",
                            ),
                            ("manual.work_logged", "Manual work logged"),
                        ],
                        max_length=64,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=32)),
                ("to_status", models.CharField(blank=True, max_length=32)),
                (
                    "actor_kind",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("customer", "Customer"),
                            ("operator", "Operator"),
                        ],
                        default="system",
                        max_length=16,
                    ),
                ),
                ("actor_ref", models.CharField(blank=True, max_length=150)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManualWorkLog",
            fields=[],
            options={
                "verbose_name": "Manual work log",
                "verbose_name_plural": "Manual work logs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.orderevent",),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["order", "created_at"], name="core_orderevent_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="core_orderevent_type_idx"
            ),
        ),
    ]
