# DRF-2053 final delivery: DELIVERY_IN_PROGRESS / DELIVERED order statuses
# and the FinalDelivery audit run. Depends on 0007_qc (DRF-2052), which owns
# the READY_FOR_DELIVERY status choice the delivery flow enters from.
# Generated by Django 5.0.6 on 2026-09-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_qc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("awaiting_photos", "Awaiting photos"),
                    ("ready_for_checkout", "Ready for checkout"),
                    ("awaiting_payment", "Awaiting payment"),
                    ("paid", "Paid"),
                    ("preview_generating", "Preview generating"),
                    ("internal_preview_review", "Internal preview review"),
                    ("preview_review", "Preview review"),
                    ("revision_requested", "Revision requested"),
                    ("revision_generating", "Revision generating"),
                    ("pack_generating", "Pack generating"),
                    ("quality_control", "Quality control"),
                    ("ready_for_delivery", "Ready for delivery"),
                    ("delivery_in_progress", "Delivery in progress"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="FinalDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("max", "MAX")],
                        max_length=20,
                    ),
                ),
                ("attempt", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="in_progress",
                        max_length=32,
                    ),
                ),
                ("results", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_deliveries",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "ordering": ["order_id", "attempt"],
            },
        ),
        migrations.AddConstraint(
            model_name="finaldelivery",
            constraint=models.UniqueConstraint(
                fields=("order", "attempt"), name="uniq_final_delivery_attempt"
            ),
        ),
    ]
