# MAX Pilot consent gate: persist which consent text the customer accepted
# and when, per order. Depends on 0009_order_event (DRF-2055), the head of
# the core migration graph on dev.
# Generated by Django 5.0.6 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_order_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="consent_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="consent_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
