# DRF-2084: Russian verbose labels for Order.Status (Production Console).
# Choice labels only — no data or schema change at the database level.
# Generated by Django 5.2.17 on 2026-09-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('awaiting_photos', 'Ждём фото'), ('ready_for_checkout', 'Готов к оплате'), ('awaiting_payment', 'Ждём оплату'), ('paid', 'Оплачен'), ('preview_generating', 'Генерация превью'), ('internal_preview_review', 'Внутренняя проверка превью'), ('preview_review', 'Ждём ответ клиента'), ('revision_requested', 'Правка запрошена'), ('revision_generating', 'Генерация правки'), ('pack_generating', 'Производство'), ('quality_control', 'Контроль качества'), ('ready_for_delivery', 'Готов к доставке'), ('delivery_in_progress', 'Доставка'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён'), ('failed', 'Ошибка')], default='draft', max_length=32),
        ),
    ]
