# «Сменить одежду» (owner GO 2026-09-20): new Revision.Category CLOTHES.
# Choice labels only — no data or schema change at the database level
# (CharField max_length unchanged); kept so `makemigrations --check` stays green.
# Generated by Django 5.0.6 on 2026-09-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_order_status_labels_ru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revision",
            name="category",
            field=models.CharField(
                choices=[
                    ("face", "Face"),
                    ("hair", "Hair"),
                    ("body", "Body"),
                    ("detail", "Detail"),
                    ("colors", "Colors"),
                    ("style_expectation", "Style expectation"),
                    ("clothes", "Clothes"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
