# DRF-2164 Photo Suitability Gate: OrderPhoto.metadata (JSON, default {}) —
# what the gate measured on accept. ADD COLUMN with a constant default:
# Postgres ≥ 11 rewrites no rows (metadata-only change), no data migration.
# Generated by Django 5.0.6 on 2026-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_revision_category_clothes"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderphoto",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
